selected = "reverse"
description = "dim"
match_highlight = "bold"
item_text = ""
kind_icon = "dim"
scrollbar = "dim"
border = "dim"
feedback_loading = "dim"
feedback_empty = "dim"
feedback_error = "dim fg:196"
background = ""
description_box_background = ""
