selected = "fg:#F8F8F2 bg:#44475A bold"
description = "fg:#6272A4"
match_highlight = "fg:#F1FA8C bold"
item_text = "fg:#F8F8F2"
kind_icon = "fg:#BD93F9"
scrollbar = "fg:#6272A4"
border = "fg:#44475A"
feedback_loading = "fg:#6272A4"
feedback_empty = "fg:#6272A4"
feedback_error = "fg:#FF5555 bold"
background = "bg:#282A36"
description_box_background = "bg:#21222C"
