selected = "fg:#ebdbb2 bg:#504945 bold"
description = "fg:#a89984"
match_highlight = "fg:#fabd2f bold"
item_text = "fg:#ebdbb2"
kind_icon = "fg:#d3869b"
scrollbar = "fg:#665c54"
border = "fg:#504945"
feedback_loading = "fg:#a89984"
feedback_empty = "fg:#a89984"
feedback_error = "fg:#fb4934 bold"
background = "bg:#282828"
description_box_background = "bg:#1d2021"
