selected = "fg:#ECEFF4 bg:#434C5E bold"
description = "fg:#81A1C1"
match_highlight = "fg:#EBCB8B bold"
item_text = "fg:#ECEFF4"
kind_icon = "fg:#88C0D0"
scrollbar = "fg:#4C566A"
border = "fg:#434C5E"
feedback_loading = "fg:#81A1C1"
feedback_empty = "fg:#81A1C1"
feedback_error = "fg:#BF616A bold"
background = "bg:#2E3440"
description_box_background = "bg:#242933"
