selected = "fg:#c0caf5 bg:#292e42 bold"
description = "fg:#737aa2"
match_highlight = "fg:#e0af68 bold"
item_text = "fg:#c0caf5"
kind_icon = "fg:#7dcfff"
scrollbar = "fg:#3b4261"
border = "fg:#292e42"
feedback_loading = "fg:#737aa2"
feedback_empty = "fg:#737aa2"
feedback_error = "fg:#f7768e bold"
background = "bg:#1a1b26"
description_box_background = "bg:#16161e"
